#!/usr/bin/env python3
"""Write the wiki's API reference (API-reference.md) from docs/openapi.json.

Every route, grouped as Swagger groups them, with what it is for, its parameters, and whether
an agent's key opens it. Written by hand it fell 53 routes behind (the audit of 2026-10-07);
generated, it cannot. `--check` exits 1 when the page in the wiki is not what this would write.

    python3 scripts/apiref.py ~/argus.wiki/API-reference.md
    python3 scripts/apiref.py --check ~/argus.wiki/API-reference.md
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


def agent_opens(method: str, path: str) -> bool:
    from app.auth import AGENT_ROUTES, ASK_PREFIX, REQUEST_PREFIX, TODO_PREFIX
    if (method, path) in AGENT_ROUTES:
        return True
    probe = path.replace("{ident}", "x").replace("{ask_id}", "x")
    return (method == "GET" and (probe.startswith(ASK_PREFIX) or probe.startswith(REQUEST_PREFIX))
            and probe.count("/") == path.count("/")) or (method == "PATCH" and probe.startswith(TODO_PREFIX))


def first_paragraph(text: str) -> str:
    para = (text or "").strip().split("\n\n")[0]
    return " ".join(para.split())


def render(spec: dict) -> str:
    tags = {t["name"]: t.get("description", "") for t in spec.get("tags", [])}
    groups: dict[str, list] = {}
    for path, ops in spec["paths"].items():
        for verb, op in ops.items():
            if verb == "head":
                continue
            groups.setdefault((op.get("tags") or ["Other"])[0], []).append((path, verb.upper(), op))
    order = [t for t in tags if t in groups] + sorted(g for g in groups if g not in tags)
    count = sum(len(v) for v in groups.values())
    out = [
        "# API reference",
        "",
        "<!-- Generated by scripts/apiref.py from docs/openapi.json. Do not edit by hand: change the",
        "     route's summary or docstring in app/, then run `python3 scripts/apiref.py <this file>`. -->",
        "",
        f"Every route of this copy of Argus — {count} — grouped as the live Swagger page groups them",
        "(Settings → Go to → *The API*, `/api.html` on your own server, with **Try it out**). What each is",
        "*for*, and the ideas behind them, are in [The API](The-API). **Agent** marks the routes an",
        "agent's key opens ([An agent driving Argus](An-agent-driving-Argus)); everything is open to the",
        "token from the config and to a device's token, except managing devices (config token only).",
        "All of it is under `/api`, behind the token, except `/proxy/<port>/` (its own gate).",
        "",
    ]
    for g in order:
        out += [f"## {g}", ""]
        if tags.get(g):
            out += [tags[g], ""]
        out += ["| | Route | What it does | Agent |", "|---|---|---|---|"]
        for path, verb, op in sorted(groups[g], key=lambda x: (x[0], x[1])):
            params = [p["name"] + ("" if p.get("required") else "?") for p in op.get("parameters", [])
                      if p.get("in") == "query"]
            what = op.get("summary", "")
            detail = first_paragraph(op.get("description", ""))
            if detail and detail.lower().rstrip(".") != what.lower().rstrip("."):
                what += f" — {detail}"
            what = what.replace("|", "\\|")
            route = f"`{path}`" + (f" `?{'&'.join(params)}`" if params else "")
            out.append(f"| {verb} | {route} | {what} | {'✅' if agent_opens(verb, path) else ''} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str]) -> int:
    check = "--check" in argv
    args = [a for a in argv if a != "--check"]
    if not args:
        print(__doc__)
        return 2
    target = Path(args[0]).expanduser()
    text = render(json.loads((ROOT / "docs" / "openapi.json").read_text()))
    if check:
        if not target.exists() or target.read_text() != text:
            print(f"{target} is not current: python3 scripts/apiref.py {target}")
            return 1
        print(f"{target} is current")
        return 0
    target.write_text(text)
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
